server:
  port: 8084

spring:
  application:
    name: medical-record-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/medicaldb}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: digitalschool
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

