server:
  port: 8081

spring:
  application:
    name: doctor-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/doctordb}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: digitalschool
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update