apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: api-gateway
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api-gateway
  template:
    metadata:
      labels:
        io.kompose.service: api-gateway
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: api-gateway
          image: ghcr.io/tema-e-diplomes/dental-clinic/api-gateway:latest
          ports:
            - containerPort: 8080
          env:
            - name: APPOINTMENT_SERVICE_URL
              value: http://appointment-service:8083
            - name: DOCTOR_SERVICE_URL
              value: http://doctor-service:8081
            - name: MEDICAL_RECORD_SERVICE_URL
              value: http://medical-record-service:8084
            - name: PATIENT_SERVICE_URL
              value: http://patient-service:8082
            - name: KEYCLOAK_ISSUER
              value: http://localhost:8085/auth/realms/dental-clinic
            - name: KEYCLOAK_JWKS
              value: http://keycloak:8085/auth/realms/dental-clinic/protocol/openid-connect/certs
      restartPolicy: Always