apiVersion: v1
kind: Service
metadata:
  name: doctor-service     
spec:
  selector:
    io.kompose.service: doctor-service       
  ports:
    - protocol: TCP
      port: 8081            
      targetPort: 8081       
  type: ClusterIP            