apiVersion: v1
data:
  realm-export.json: |-
    {
        "realm": "dental-clinic",
        "enabled": true,
        "clients": [
            {
                "clientId": "dental-frontend",
                "enabled": true,
                "publicClient": true,
                "directAccessGrantsEnabled": true,
                "webOrigins": [
                    "*"
                ],
                "redirectUris": [
                    "http://localhost:5173/*",
                    "http://localhost:8080/*"
                ],
                "standardFlowEnabled": true
            }
        ],
        "roles": {
            "realm": [
                {
                    "name": "DOCTOR"
                },
                {
                    "name": "STAFF"
                },
                {
                    "name": "PATIENT"
                }
            ]
        },
        "users": [
            {
                "username": "admin",
                "enabled": true,
                "email": "admin@dental.com",
                "firstName": "Admin",
                "lastName": "User",
                "credentials": [
                    {
                        "type": "password",
                        "value": "admin",
                        "temporary": false
                    }
                ],
                "realmRoles": [
                    "DOCTOR",
                    "STAFF"
                ]
            }
        ]
    }
kind: ConfigMap
metadata:
  labels:
    app: keycloak
  name: keycloak-cm0
