apiVersion: v1
kind: Service
metadata:
  labels:
    app: medical-record-service
  name: medical-record-service
spec:
  ports:
    - name: "8084"
      port: 8084
      targetPort: 8084
  selector:
    app: medical-record-service
