apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: patient-service
  name: patient-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: patient-service
  template:
    metadata:
      labels:
        io.kompose.service: patient-service
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - env:
            - name: SPRING_DATASOURCE_PASSWORD
              value: digitalschool
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/patientdb
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
          image: ghcr.io/tema-e-diplomes/dental-clinic/patient-service:latest
          name: patient-service
          ports:
            - containerPort: 8082
              protocol: TCP
      restartPolicy: Always
