apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: pgadmin
  name: pgadmin
spec:
  ports:
    - name: "8089"
      port: 8089
      targetPort: 80
  selector:
    io.kompose.service: pgadmin
