apiVersion: v1
data:
  01-init-databases.sql: |-
    CREATE DATABASE doctordb;
    CREATE DATABASE patientdb;
    CREATE DATABASE appointmentdb;
    CREATE DATABASE medicaldb;
    CREATE DATABASE keycloak;
kind: ConfigMap
metadata:
  labels:
    app: postgres
  name: postgres-cm1
